# MNK

### r(xy) = -1 < r < 1  (влияет прямо или обратно)

    (0 - 0.3 -> слабая)
    (0.3 - 0.5 -> средняя)
    (0.5 - 0.7 -> умеренная)
    (0.7 - 1 -> очень сильная)

### R(xy) 0 < R < 1 (%)
    Влияние X на Y (в процентах)

### A(i) 0 < A < 100 (%)

    ( < 10% -> модель устойчива)
    ( > 10% -> модель устойчива)

In [4]:
import numpy as np
import pandas as pd

In [122]:
corr: float # rb
determination: float #R = (rxy)^2
appeoximation_error: float # A

In [123]:
ans = dict()

## f(x) = Kx + b (Линейная)

In [124]:
x = np.array(
    [50, 60, 70, 100, 40, 70, 40, 80, 90, 60]
)

y = np.array(
    [10, 12, 12, 19, 9, 14, 8, 16, 15, 11]
)

In [125]:
# Basic calculations
xy: np.array = x * y
y2 = np.power(y, 2)
x2 = np.power(x, 2)

# Cherta functions
x_mean = np.mean(x)
y_mean = np.mean(y)
xy_mean = np.mean(xy)
y2_mean = np.mean(y2)
x2_mean = np.mean(x2)

# linear coef
a: float = (xy_mean - x_mean * y_mean) / (x2_mean - x_mean * x_mean)

# linear intercept
b: float = y_mean - a * x_mean

# Linear function f(x)
y_func = a * x + b

# appeoximation error (non %)
A = np.abs( (y - y_func) / y_func )
A_mean = np.mean(A) 

# correlation (non %)
r_xy = a * np.sqrt( (x2_mean - (x_mean * x_mean)) / (y2_mean - (y_mean * y_mean)) )

# determination (non %)
R = r_xy * r_xy


In [126]:
r_xy, R, A_mean

(0.9635749559417132, 0.9284766957180745, 0.05714011490714908)

In [127]:
ans["Линейная"] = {"r(xy)": r_xy, "R": R, "A(i)": A_mean}

## f(x) = a * x^b (степенная)

In [43]:
x = np.array(
    [99, 82, 77, 69, 52, 44, 31, 29, 28, 27.5]
)

y = np.array(
    [100, 115, 210, 270, 323, 478, 544, 564, 570, 574]
)

In [44]:
# Precalculations
X = np.log10(x)
Y = np.log10(y)

# Basic calculations

x_mean = np.mean(x)
y_mean_ = np.mean(y)
XY = X * Y
Y2 = np.power(Y, 2)
X2 = np.power(X, 2)

# Cherta functions
X_mean = np.mean(X)
Y_mean = np.mean(Y)
XY_mean = np.mean(XY)
Y2_mean = np.mean(Y2)
X2_mean = np.mean(X2)


# coef
A_: float = (XY_mean - X_mean * Y_mean) / (X2_mean - X_mean * X_mean)

# intercept
B_: float = Y_mean - A_ * X_mean

# function f(x)
y_func = np.power(10, B_) * np.power(x, A_)

# (y - y_func)^2
flag1 = (y - y_func) * (y - y_func)

# (y - y_mean)^2
flag2 = (y - y_mean_) * (y - y_mean_)

# Correlation
r_xy = np.sqrt( 1 - np.sum(flag1) / np.sum(flag2) )


# appeoximation error (non %)
A = np.abs( (y - y_func) / y_func )
A_mean = np.mean(A) 

# determination (non %)
R = r_xy * r_xy


619.9024999999997

24.897841271885394

In [39]:
A_

-1.2755192791605046

In [40]:
B_

4.647729937992366

In [38]:
x

array([99. , 82. , 77. , 69. , 52. , 44. , 31. , 29. , 28. , 27.5])

In [26]:
x_mean

53.85

In [14]:
y

array([100, 115, 210, 270, 323, 478, 544, 564, 570, 574])

In [29]:
y_mean_

374.8

In [15]:
X

array([1.99563519, 1.91381385, 1.88649073, 1.83884909, 1.71600334,
       1.64345268, 1.49136169, 1.462398  , 1.44715803, 1.43933269])

In [27]:
X_mean

1.6834495299917702

In [16]:
Y

array([2.        , 2.06069784, 2.32221929, 2.43136376, 2.50920252,
       2.6794279 , 2.7355989 , 2.7512791 , 2.75587486, 2.75891189])

In [30]:
Y_mean

2.5004576069941726

In [17]:
XY

array([3.99127039, 3.94379207, 4.38084516, 4.47091105, 4.30579992,
       4.40351295, 4.07976741, 4.02346505, 3.98818643, 3.97099209])

In [18]:
XY_mean

4.155854251518199

In [19]:
X2

array([3.98255983, 3.66268346, 3.55884726, 3.38136598, 2.94466748,
       2.7009367 , 2.2241597 , 2.1386079 , 2.09426637, 2.0716786 ])

In [31]:
X2_mean

2.875977327867673

In [21]:
Y2

array([4.        , 4.24647559, 5.39270245, 5.91152975, 6.2960973 ,
       7.17933385, 7.48350134, 7.56953671, 7.59484622, 7.61159483])

In [33]:
Y2_mean

6.328561804514203

In [23]:
y_func

array([126.54901615, 160.92498323, 174.37115654, 200.55914582,
       287.69650769, 356.0199745 , 556.50535192, 605.91694468,
       633.6536911 , 648.38556544])

In [24]:
A

array([0.20979236, 0.28538131, 0.20432762, 0.34623629, 0.12271088,
       0.3426213 , 0.02247122, 0.06917936, 0.10045502, 0.11472428])

In [25]:
A_mean

0.18178996229721783

In [41]:
r_xy, R, A_mean

(0.9441962206088796, 0.8915065030120921, 0.18178996229721783)

In [130]:
ans["Степенная"] = {"r(xy)": r_xy, "R": R, "A(i)": A_mean}

## f(x) = a * b ^ x (показательная)

In [131]:
# Precalculations
Y = np.log10(y)

# Basic calculations
x_mean = np.mean(x)
y_mean__ = np.mean(y)
Yx: np.array = Y * x
Y2 = np.power(Y, 2)
x2 = np.power(x, 2)

# Cherta functions
x_mean = np.mean(x)
Y_mean = np.mean(Y)
Yx_mean = np.mean(Yx)
Y2_mean = np.mean(Y2)
x2_mean = np.mean(x2)


# сoef
A: float = (Yx_mean - x_mean * Y_mean) / (x2_mean - x_mean * x_mean)

# intercept
B: float = Y_mean - A * x_mean

# Exponentional function f(x)
y_func = np.power(10, A * x + B)

# (y - y_func)^2
flag1 = (y - y_func) * (y - y_func)

# (y - y_mean)^2
flag2 = (y - y_mean__) * (y - y_mean__)

# Correlation
r_xy = np.sqrt( 1 - (np.sum(flag1) / np.sum(flag2)) )

# appeoximation error (non %)
A = np.abs( (y - y_func) / y_func )
A_mean = np.mean(A) 

# determination (non %)
R = r_xy * r_xy


In [132]:
r_xy, R, A_mean

(0.9617641785460881, 0.9249903351344316, 0.05640402889875771)

In [133]:
ans["Показательная"] = {"r(xy)": r_xy, "R": R, "A(i)": A_mean}

## (Гиперболическая)

In [134]:
z = 1 / x
zy = z * y
z2 = np.power(z, 2)
y2 = np.power(y, 2)

# Cherta functions
x_mean = np.mean(x)
y_mean___ = np.mean(y)
z_mean = np.mean(z)
y_mean = np.mean(y)
zy_mean = np.mean(zy)
y2_mean = np.mean(y2)
z2_mean = np.mean(z2)

# coef
a: float = (zy_mean - z_mean * y_mean) / (z2_mean - z_mean * z_mean)

# intercept
b: float = y_mean - a * z_mean

# function f(x)
y_func = b + a * z

# (y - y_func)^2
flag1 = (y - y_func) * (y - y_func)

# (y - y_mean)^2
flag2 = (y - y_mean___) * (y - y_mean___)

# Correlation
r_xy = np.sqrt( 1 - (np.sum(flag1) / np.sum(flag2)) )

# appeoximation error (non %)
A = np.abs( (y - y_func) / y_func )
A_mean = np.mean(A) 

# determination (non %)
R = r_xy * r_xy

In [135]:
r_xy, R, A_mean

(0.9156595603719371, 0.8384324305005291, 0.0861766382026408)

In [136]:
ans["Гиперболическая"] = {"r(xy)": r_xy, "R": R, "A(i)": A_mean}

## RESULTS

In [141]:
for name, d in ans.items():
    print(name)
    for k, w in d.items():
        print(f"{k}: {w}")
    print("\n")

Линейная
r(xy): 0.9635749559417132
R: 0.9284766957180745
A(i): 0.05714011490714908


Степенная
r(xy): 0.9618776164881118
R: 0.925208549100851
A(i): 0.05873857552967188


Показательная
r(xy): 0.9617641785460881
R: 0.9249903351344316
A(i): 0.05640402889875771


Гиперболическая
r(xy): 0.9156595603719371
R: 0.8384324305005291
A(i): 0.0861766382026408


